export const BATSDB = [
  {
    id: 0,
    state: "back",
    width: 128 * 0.8,
    height: 256 * 0.8,
    src: "../../src/img/bat/cage_back.png",
  },
  {
    id: 1,
    state: "doorClosed",
    width: 128 * 0.8,
    height: 256 * 0.8,
    src: "../../src/img/bat/cage_front.png",
  },
  {
    id: 2,
    state: "doorOpened",
    width: 189 * 0.8,
    height: 256 * 0.8,
    src: "../../src/img/bat/cage_open.png",
  },
  {
    id: 3,
    state: "blackBat",
    width: 47,
    height: 42,
    widthSize: 47,
    heightSize: 42,
    frameReset: 4,
    initialFrame: 4,
    stepFrames: 2,
    src: "../../src/img/bat/blackBat.png",
  },
  {
    id: 4,
    state: "redBat",
    width: 47.5,
    height: 36,
    widthSize: 47.5,
    heightSize: 36,
    frameReset: 2,
    initialFrame: 2,
    stepFrames: 4,
    src: "../../src/img/bat/redBat.png",
  },
  {
    id: 5,
    state: "blueBat",
    width: 47,
    height: 34,
    widthSize: 47,
    heightSize: 34,
    frameReset: 4,
    initialFrame: 4,
    stepFrames: 2,
    src: "../../src/img/bat/blueBat.png",
  },
];
