export const MONSTERDB = [
  {
    id: 0,
    state: "walk",
    width: 128,
    height: 130,
    widthSize: 128,
    heightSize: 130,
    frameReset: 5,
    initialFrame: 5,
    stepFrames: 9,
    src: "../../src/img/monster/monster_walk.png",
  },
  {
    id: 1,
    state: "attack",
    width: 218,
    height: 145,
    widthSize: 218,
    heightSize: 145,
    frameReset: 9,
    initialFrame: 9,
    stepFrames: 2,
    src: "../../src/img/monster/monster_attack.png",
  },
  {
    id: 2,
    state: "dead",
    width: 142,
    height: 144,
    widthSize: 142,
    heightSize: 144,
    frameReset: 12,
    initialFrame: 12,
    stepFrames: 6,
    src: "../../src/img/monster/monster_dead.png",
  },
  {
    id: 3,
    state: "idle",
    width: 100.7,
    height: 144,
    widthSize: 100.7,
    heightSize: 144,
    frameReset: 12,
    initialFrame: 12,
    stepFrames: 6,
    src: "../../src/img/monster/monster_idle.png",
  },
];
