export const PLAYERDB = [
  {
    id: 0,
    state: "idle",
    width: 67,
    height: 93,
    widthSize: 67 * 1.2,
    heightSize: 93 * 1.2,
    frameReset: 6,
    initialFrame: 6,
    stepFrames: 9,
    src: "../../src/img/player_idle.png",
  },
  {
    id: 1,
    state: "run",
    width: 77,
    height: 81,
    widthSize: 77 * 1.4,
    heightSize: 81 * 1.4,
    frameReset: 6,
    initialFrame: 6,
    stepFrames: 7,
    src: "../../src/img/player_run.png",
  },
  {
    id: 2,
    state: "attack",
    width: 115,
    height: 93,
    widthSize: 115 * 1.2,
    heightSize: 93 * 1.2,
    frameReset: 3,
    initialFrame: 3,
    stepFrames: 6,
    src: "../../src/img/player_attack.png",
  },
  {
    id: 3,
    state: "bomb",
    width: 122,
    height: 134,
    widthSize: 122 * 1.2,
    heightSize: 134 * 1.2,
    frameReset: 7,
    initialFrame: 7,
    stepFrames: 6,
    src: "../../src/img/player_bomb.png",
  },
  {
    id: 4,
    state: "takeHits",
    width: 101,
    height: 96,
    widthSize: 101 * 1.2,
    heightSize: 96 * 1.2,
    frameReset: 7,
    initialFrame: 7,
    stepFrames: 5,
    src: "../../src/img/player_takeHits.png",
  },
  {
    id: 5,
    state: "dead",
    width: 122,
    height: 96,
    widthSize: 122 * 1.2,
    heightSize: 96 * 1.2,
    frameReset: 7,
    initialFrame: 7,
    stepFrames: 8,
    src: "../../src/img/player_dead.png",
  },
  {
    id: 6,
    state: "fire",
    width: 72.75,
    height: 137,
    widthSize: 72.75 * 1.2,
    heightSize: 137 * 1.2,
    frameReset: 12,
    initialFrame: 12,
    stepFrames: 8,
    src: "../../src/img/player_fire.png",
  },
  {
    id: 7,
    state: "resurrection",
    width: 97,
    height: 136,
    widthSize: 97 * 2,
    heightSize: 136 * 2,
    frameReset: 9,
    initialFrame: 9,
    stepFrames: 8,
    src: "../../src/img/player_resurrection.png",
  },
];
