const PLAYERDB = [
  {
    state: "idle",
    width: 67,
    height: 93,
    frameReset: 6,
    initialFrame: 6,
    stepFrames: 9,
    src: "../../src/img/player_idle.png",
  },
  {
    state: "run",
    width: 77,
    height: 81,
    frameReset: 6,
    initialFrame: 6,
    stepFrames: 7,
    src: "../../src/img/player_run.png",
  },
  {
    state: "attack",
    width: 115,
    height: 93,
    frameReset: 11,
    initialFrame: 11,
    stepFrames: 6,
    src: "../../src/img/player_attack.png",
  },
  {
    state: "shoot",
    width: 116,
    height: 108,
    frameReset: 2,
    initialFrame: 2,
    stepFrames: 7,
    src: "../../src/img/player_shoot.png",
  },
  {
    state: "bomb",
    width: 122,
    height: 134,
    frameReset: 7,
    initialFrame: 7,
    stepFrames: 6,
    src: "../../src/img/player_bomb.png",
  },
  {
    state: "takeHits",
    width: 101,
    height: 96,
    frameReset: 7,
    initialFrame: 7,
    stepFrames: 5,
    src: "../../src/img/player_takeHits.png",
  },
  {
    state: "dead",
    width: 122,
    height: 96,
    frameReset: 7,
    initialFrame: 7,
    stepFrames: 8,
    src: "../../src/img/player_dead.png",
  },
];
